let data = [
    {
      name: "James King",
      title: "President and CEO",
      office: "781-000-0002",
      mobile: "617-000-0002",
      email: "jayking@fakeemail.com",
      headshot: "./images/images/headshot0.jpeg",
      id: 1,
    },
    {
      name: "Julie Taylor",
      title: "VP of Marketing",
      office: "781-000-0002",
      mobile: "617-000-0002",
      email: "jayking@fakeemail.com",
      headshot: "./images/images/headshot1.jpeg",
      id: 2,
    },
    {
      name: "Eugene Lee",
      title: "CFO",
      office: "781-000-0002",
      mobile: "617-000-0002",
      email: "jayking@fakeemail.com",
      headshot: "./images/images/headshot2.jpeg",
      id: 3,
    },
    {
      name: "John Williams",
      title: "VP of Engineering",
      office: "781-000-0002",
      mobile: "617-000-0002",
      email: "jayking@fakeemail.com",
      headshot: "./images/images/headshot3.jpeg",
      id: 4,
    },
    {
      name: "Ray Moore",
      title: "VP of Sales",
      office: "781-000-0002",
      mobile: "617-000-0002",
      email: "jayking@fakeemail.com",
      headshot: "./images/images/headshot4.jpeg",
      id: 5,
    },
    {
      name: "Paul Jones",
      title: "QA Manager",
      office: "781-000-0002",
      mobile: "617-000-0002",
      email: "jayking@fakeemail.com",
      headshot: "./images/images/headshot5.jpeg",
      id: 6,
    },
  ];
  
  export default data;